protoc-gen-connecpy/generator/generator.go
protoc-gen-connecpy/generator/template.go

If proto files are organized in sub directories, the generated connecpy file import pb2 file in a wrong way.
For example, if the protos files are in the following directoies:
```
- apis
- api.proto 
```
The generated api_connecpy.py will import api_pb2 by `import apis/api_pb2 as _pb2`, and it is illegal.
This PR will import api_pb2 in module way, which is `import apis.api_pb2 as _pb2`

feat: generate connecpy api from proto in package

---

example/haberdasher_connecpy.py
example/haberdasher_pb2.py
example/haberdasher_pb2.pyi
protoc-gen-connecpy/generator/template.go

This PR changes the name of a generated service protocol class as the following:
original: `<Service Name>Service` Protocol
new:      `<Service Name>` Protocol
[This](https://github.com/i2y/connecpy/pull/5/files#diff-b1ebd8e6bde6512cc22899ce45289cd0b9605d7f8d9d41b5de5830032c68f530R18) is the actual example.
In Protocol Buffers definitions, a service often has the service postfix (e.g., `GreeterService`). In that case, if the protocol class name becomes `GreeterServiceService`, it appears awkward.

chore(generator): change the name of a generated service protocol class

---

example/haberdasher_connecpy.py
example/haberdasher_pb2.py
example/haberdasher_pb2.pyi
protoc-gen-connecpy/generator/generator.go
protoc-gen-connecpy/generator/template.go
src/connecpy/server.py

This PR adds `serviceName` method to a generated server class.
For example, it returns `foo.v1.BarServcie` for `BarServer` class of `foo.v1` package .
Currently, users of a generated server class don't have the way to get the service name.

feat: add `serviceName` method to server class

---

pyproject.toml

SSIA
I changed the version number to 1.0.7 just before, but that was a mistake 😓 
We introduced a new feature, so it needs to be a minor version change, not a patch version. Therefore, I will change the version number to 1.1.0 (same content as 1.0.7).

chore(release): bump version to 1.1.0

---

pyproject.toml

to avoid the following issue:
```console
> rye publish
Uploading distributions to https://upload.pypi.org/legacy/                                   
ERROR    InvalidDistribution: Metadata is missing required fields: Name, Version.
Make sure the distribution includes the files where those fields are specified, and 
is using a supported Metadata-Version: 1.0, 1.1, 1.2, 2.0, 2.1, 2.2, 2.3.
error: failed to publish files
```

fix: use of the latest version of hatchling

---

pyproject.toml
src/connecpy/wsgi.py
uv.lock

This PR modifies `extract_headers` function in `wsgi.py` to properly retrieve headers such as `CONTENT_TYPE` by changing the logic.
To address the issue where `CONTENT_TYPE` was not being correctly obtained from WSGI environment.

fix(wsgi): fix wrong request headers

---

src/connecpy/wsgi.py

This pull request includes a small change to the `src/connecpy/wsgi.py` file. The change initializes the `compressor` variable to `None` before it is potentially assigned a value within a conditional block. This ensures that the variable is defined even if the condition is not met.
Changes in `src/connecpy/wsgi.py`:
* Initialized the `compressor` variable to `None` before the conditional block to ensure it is defined.

fix(wsgi): an uninitialized local variable `compressor`

---

pyproject.toml
uv.lock

This pull request includes a small change to the `pyproject.toml` file. The change updates the version number of the `connecpy` project from `1.4.0` to `1.4.1`.

chore: release 1.4.1

---

src/connecpy/_protocol.py
src/connecpy/asgi.py
src/connecpy/async_client.py
src/connecpy/client.py
src/connecpy/errors.py
src/connecpy/exceptions.py
src/connecpy/wsgi.py
test/test_errors.py

I noticed error handling is not consistent with connect protocol - being an implementation of it, I think it's necessary to follow it exactly. I have reverse engineered the handling from connect-go, putting it in an implementation detail module `_protocol` to encapsulate it as best as possible.
The most important references are the mapping between connect code and HTTP
https://github.com/connectrpc/connect-go/blob/main/protocol_connect.go#L1269
https://github.com/connectrpc/connect-go/blob/main/protocol.go#L401
Some are different from the current mapping in
https://github.com/i2y/connecpy/blob/main/src/connecpy/errors.py#L41
but I feel it must be fixed for compatibility. Let me know if you rely on the old mapping and I can try to provide some compatibility layer, hopefully temporarily.

fix: handle errors following connect protocol

---

src/connecpy/_protocol.py
src/connecpy/asgi.py
src/connecpy/base.py
src/connecpy/context.py
src/connecpy/encoding.py
src/connecpy/errors.py
src/connecpy/exceptions.py
src/connecpy/server.py
src/connecpy/wsgi.py
test/test_errors.py

I have followed connect-go handler code to better reproduce its error handling outside connect protocol
https://github.com/connectrpc/connect-go/blob/main/handler.go#L174
In addition, non-matched paths are handled as straight 404 in generated code, not in framework for it, so I reproduced that too. Now, there aren't any out-of-spec error codes

fix: remove non-spec error codes

---

example/starlette_mount.py
pyproject.toml
src/connecpy/asgi.py
src/connecpy/base.py
uv.lock

I was interested in adding a starlette example and randomly realized that there is currently a dependency on it for two reasons
- Executing blocking service in asgi server which is trivial with asyncio instead (basically what starlette is calling except with anyio)
- I wonder if we need this functionality anyways, at least a blocking service wouldn't pass type-check I think
- Collect request body. Less trivial to replace but I think it's worth it to make it a pure ASGI app without dependencies
Most production users I guess will still use the ASGI app with starlette though, if nothing else a health endpoint is very commonly needed and I added an example of it

feat: remove starlette dependency and add example instead

---

example/starlette_mount.py

This PR adds type cast to resolve pyright error in starlette_mount.py on Ubuntu CI.
- Starlette and asgiref use incompatible ASGI type definitions
- Cast is a no-op at runtime but satisfies the type checker

chore: add type cast for Starlette ASGI compatibility

---

src/connecpy/wsgi.py

- Optimize read_chunked() in WSGI to use list + join pattern instead of byte concatenation
- Matches the efficient implementation already used in ASGI
- Byte concatenation (body += chunk) creates new objects on each iteration, resulting in O(n²) complexity
- List append + join is O(n) and more memory efficient for large chunked payloads

perf: optimize WSGI read_chunked() to match ASGI's efficient implementation

---

.github/workflows/ci.yaml
example/pyproject.toml
noextras/pyproject.toml
noextras/test/test_compression_default.py
pyproject.toml
src/connecpy/_client_async.py
src/connecpy/_client_shared.py
src/connecpy/_client_sync.py
src/connecpy/_compression.py
src/connecpy/_server_async.py
src/connecpy/_server_sync.py
test/test_errors.py
test/test_roundtrip.py
uv.lock

The main feature of this is to validate content encoding, so if a bad one is returned from server we throw an error instead of trying to parse as identity (httpx ignores unknown encoding it seems). This passes another conformance test.
Also refactors compression to look closer to Codec, and makes brotli and zstandard optional dependencies which I think is good practice and matches other connect implementations

feat: validate content encoding in client

---

.github/workflows/release.yaml

I can't verify this well so sorry if it has issues, but I think it should generally work. How about automating the release process?
https://github.com/pypa/gh-action-pypi-publish
If not done yet, it seems you would need to update the pypi settings to add github actions as a trusted publisher
https://docs.pypi.org/trusted-publishers/adding-a-publisher/

chore: add release workflow on tag

---

conformance/test/client.py
conformance/test/config.yaml
conformance/test/test_server.py

Unfortunately unless httpx adds support for full duplex bidi in https://github.com/encode/httpx/issues/1150, we can only support half duplex.

test: add tests for half duplex bidi

---

conformance/test/connectrpc/conformance/v1/service_connecpy.py
example/example/haberdasher_connecpy.py
example/example/haberdasher_edition_2023_connecpy.py
protoc-gen-connecpy/generator/template.go
src/connecpy/_server_shared.py
src/connecpy/_server_sync.py
src/connecpy/server.py

I randomly noticed `getattr` suppressing type checking of the generated code. I removed it and fixed the typing by defining a separate `EndpointSync`

chore: remove getattr and fix endpoint types

---

conformance/test/client.py
conformance/test/config.yaml
conformance/test/server.py

Also explicitly sets config for fields that are same as default to make coverage more obvious

test: enable client TLS conformance tests

---

conformance/test/connectrpc/conformance/v1/service_connecpy.py
conformance/test/server.py
example/example/haberdasher_connecpy.py
example/example/haberdasher_edition_2023_connecpy.py
example/example/server.py
example/example/service.py
example/example/wsgi_service.py
noextras/test/test_compression_default.py
protoc-gen-connecpy/generator/template.go
pyproject.toml
src/connecpy/_client_async.py
src/connecpy/_client_shared.py
src/connecpy/_client_sync.py
src/connecpy/_interceptor_async.py
src/connecpy/_interceptor_sync.py
src/connecpy/_protocol.py
src/connecpy/_server_async.py
src/connecpy/_server_sync.py
test/test_client.py
test/test_details.py
test/test_edition_2023.py
test/test_errors.py
test/test_interceptor.py
test/test_roundtrip.py

Sorry, I thought I was done with big changes and just wanted to enable linters...
But when enabling [flake8-builtins](https://docs.astral.sh/ruff/rules/#flake8-builtins-a) I realized the interceptor protocol definition isn't good since `next` shadows a builtin. Because type checkers require the variable name to be the same, it causes user code to follow the bad practice. I renamed to `call_next`.
And then I went ahead and renamed the variable for the service to `request` to be consistent with the interceptor - I could instead rename the interceptor to `req` but it seemed better to have the more explicit name for it but let me know if otherwise.
This also enables/ignores all linters down to DJ, with a few small fixes related to them. Stopping there to make sure this interface change …

chore: rename variable name in interceptor and service protocols

---

conformance/test/client.py
conformance/test/server.py
example/example/client.py
example/example/client_sync.py
example/example/flask_mount.py
example/example/haberdasher_edition_2023_connecpy.py
example/example/routing_asgi.py
example/example/server.py
example/example/starlette_mount.py
noextras/test/test_compression_default.py
pyproject.toml
src/connecpy/_client_async.py
src/connecpy/_client_shared.py
src/connecpy/_client_sync.py
src/connecpy/_compression.py
src/connecpy/_interceptor_async.py
src/connecpy/_interceptor_sync.py
src/connecpy/_protocol.py
src/connecpy/_server_async.py
src/connecpy/_server_shared.py
src/connecpy/_server_sync.py
src/connecpy/client.py
src/connecpy/method.py
src/connecpy/server.py
test/test_client.py
test/test_details.py
test/test_errors.py
test/test_headers.py
test/test_roundtrip.py

By default, ruff follows Black's decision of never reformating code with trailing commas even if it can be compacted. This defers from other popular formatters like prettier which prioritize having just _one_ way of formatting any type of code. In practice, I think the latter is a better approach for consistency, as I see extra line breaks due to trailing commas be more accidental than not in most cases. In rare cases when really needing it, often it's appropriate to add a `# ` comment or similar.

chore: format without trailing commas

---

RATIONALE.md
protoc-gen-connecpy/pyproject.toml
protoc-gen-connecpy/scripts/generate_wheels.py
protoc-gen-connecpy/uv.lock
pyproject.toml

For users that only need Python, being able to fetch the plugin from pypi as with other dependencies is convenient. Because the binaries are statically compiled, this is actually pretty trivial, though we need a script to go through the supported archs.
I didn't wire up to the release flow since I guess we would need your PyPi access restored to make a new package? Let me know any thoughts on what we can do for it.
I also started a rationale doc, a practice I learned from an OSS friend @codefromthecrypt. Hopefully it's interesting documentation.

chore: add script to generate wheels for protoc-gen-connecpy

---

protoc-gen-connecpy/pyproject.toml
protoc-gen-connecpy/scripts/generate_wheels.py
protoc-gen-connecpy/uv.lock

Now that uv's fixed and generates correct wheels, we can use the `wheel` command to tag instead of manual operation.
Also went ahead and just matched the linux tags for uv rather than using the very legacy manylinux1, glibc 2.17 is ~10 years old anyways so it should be fine, especially if it's good enough for uv.
https://pypi.org/project/uv/#files
@i2y By the way, for actual publishing, any ideas on it?
https://github.com/i2y/connecpy/pull/123#issue-3340071859
> I didn't wire up to the release flow since I guess we would need your PyPi access restored to make a new package? Let me know any thoughts on what we can do for it.

chore: simplify wheel generation thanks to fixed uv

---

README.md
install.sh

- Add install.sh script for easy protoc-gen-connecpy installation
- Enhance README with detailed installation instructions including the quick install option
- Support automatic platform detection (Linux/macOS, AMD64/ARM64)
- Simplify CI/CD setup: One-line installation without Go runtime, faster than go install
- Enterprise-friendly: Ideal for centralized protobuf repositories with GitHub Actions automation when an organization can't use BSR for some reason unfortunately.

chore: improve protoc plugin installation using a shell script

---

protoc-gen-connecpy/scripts/generate_wheels.py

Fixed a typo in the manylinux platform tag: manylinux2_17 → manylinux_2_17
PyPI was rejecting wheels with the invalid platform tag manylinux2_17_xxx. The correct format is manylinux_2_17_xxx with an underscore between "manylinux" and the version number.

fix: fix typo in manylinux platform tag for protoc wheels

---

protoc-gen-connecpy/scripts/generate_wheels.py

I realized the wheel binaries didn't have executable bit set. Since they're not generally invoked manually but through subprocess which doesn't need it, I don't think it affects code generation but good to fix anyways.

fix: copy file with permissions for wheel
