example/README.md

fix: typo in example/README.md

---

pyproject.toml

SSIA
(From the next release, we/I will start writing the changelog for the release)

chore(release): bump version to 1.0.3

---

pyproject.toml

chore: bump version to 1.0.5

---

src/connecpy/asgi.py
src/connecpy/errors.py

fix: two things pointed out by `rye lint`

---

pyproject.toml

chore: bump the version from 1.0.5 to 1.0.6

---

example/haberdasher_connecpy.py
protoc-gen-connecpy/generator/template.go

Adds type annotations to the request, context and response of the client RPCs.
Allows type-checking of usage of the client code, and discovery through IDE.

feat(generator): add type annotations to client classes

---

pyproject.toml

chore(release): bump version to 1.0.7

---

pyproject.toml

chore(python_package/release): bump version to 1.2.0

---

pyproject.toml
src/connecpy/compression.py

fix(compression): remove a forgotten print statement

---

pyproject.toml

chore(release): bump version to 1.2.1

---

README.md
example/README.md
example/haberdasher_connecpy.py
example/wsgi_server.py
example/wsgi_service.py
protoc-gen-connecpy/generator/template.go
pyproject.toml
src/connecpy/asgi.py
src/connecpy/base.py
src/connecpy/wsgi.py

This PR adds initial support for WSGI.
To make the library more convenient

feat: initial support for WSGI

---

README.md

This pull request includes updates to the `README.md` file to improve documentation clarity and remove outdated sections. The most important changes include updating the compression support section and removing the ASGI middleware section.
Documentation updates:
* Updated the compression support section to clarify that Connecpy supports various compression methods for both GET and POST requests/responses.
* Removed the entire ASGI middleware section, including examples of using `BrotliMiddleware`, `CompressionMiddleware`, and `GenericEncodingMiddleware`, since Connecpy now supports compression without ASGI/WSGI middleware.

fix(README): remove outdated contents

---

pyproject.toml
uv.lock

This pull request includes a small change to the `pyproject.toml` file. The change updates the version of the project from `1.4.1` to `1.4.2`.

chore: release 1.4.2

---

test/test_errors.py

Some type errors were introduced to the order of PR merges

chore: fix type errors due to merge race condition

---

pyproject.toml
src/connecpy/asgi.py
src/connecpy/compression.py
test/test_errors.py
uv.lock

This adds strong type checking of ASGI types using asgiref as a dev dependency.

chore: add ASGI typing and fix some issues

---

example/haberdasher_connecpy.py
example/service.py
example/wsgi_service.py
protoc-gen-connecpy/generator/template.go
test/test_errors.py

feat: define default implementations for protocol methods

---

src/connecpy/_protocol.py
src/connecpy/exceptions.py
test/test_details.py

Error details are required by connect protocol and verified by conformance test, so this adds support

feat: add error details

---

conformance/pyproject.toml
conformance/test/client.py
conformance/test/config.yaml
conformance/test/test_conformance.py
uv.lock

Now the only features not tested are streaming and some less common compression methods

test: enable remaining features of client conformance test

---

README.md

docs(README): fix how to install the protoc plugin

---

.github/workflows/codeql.yml

It's good to have security scanning enabled to find any quality issues

test: add codeql

---

example/requirements.txt

chore: remove unused old requirements.txt in example directory

---

.github/workflows/ci.yaml
conformance/test/client.py
conformance/test/server.py
src/connecpy/_client_async.py
src/connecpy/_server_sync.py
src/connecpy/code.py
test/test_errors.py

Added CI testing of multiple python too

fix: fix issues with Python 3.10

---

src/connecpy/_server_sync.py

When looking at codecov, realized there were some methods left over from refactorings

chore: remove some dead code

---

README.md
pyproject.toml
uv.lock

chore: release v2.2.0

---

.github/workflows/release.yaml

https://github.com/i2y/connecpy/actions/runs/17206405460/job/48807900597

fix: run goreleaser before generate_wheels.py to ensure artifacts.json exists

---

protoc-gen-connecpy/pyproject.toml
protoc-gen-connecpy/uv.lock
pyproject.toml
uv.lock

chore: release v2.3.0

---

pyproject.toml

fix: remove invalid classifier from pyproject.toml

---

docs/api.md
docs/index.md
docs/usage.md
mkdocs.yml

Improves coverage of docs by comparing with the major ones from connect-python

doc: add some more docs
